import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Student, Intervention } from '../types';

interface ReportData {
  reportType: string;
  schoolName: string;
  generatedBy: string;
  activeFilters: string[];
  date: string;
  students: Student[];
  redStudents: Student[];
  amberStudents: Student[];
  attendanceConcerns: Student[];
  behaviourEscalation: Student[];
  sendStudents: Student[];
  openInterventions: Intervention[];
  urgentInterventions: Intervention[];
  completedInterventions: Intervention[];
  escalatedInterventions: Intervention[];
  avgAttendance: number;
  successRate: number;
  resolutionRate: number;
  effectivenessRows: Array<{ actionType: string; timesUsed: number; improved: number; resolved: number; escalated: number; successRate: number }>;
  impactRows: Array<{ studentName: string; studentId: string; intervention: Intervention; baselineAttendance: number; currentAttendance: number; baselineBehaviour: number; currentBehaviour: number; outcome: string }>;
  yearGroupStats: Array<{ year: string; count: number; redCount: number; amberCount: number }>;
  subjectHotspots: Array<{ subject: string; count: number }>;
  recommendations: Array<{ title: string; detail: string; level: 'critical' | 'high' | 'medium' | 'info' }>;
  staffRows: Array<{ name: string; openCount: number; overdueCount: number; completedCount: number; successRate: number; pdLabel: string | null }>;
}

const BRAND = {
  teal: [15, 118, 110] as [number, number, number],
  tealLight: [204, 241, 238] as [number, number, number],
  slate900: [15, 23, 42] as [number, number, number],
  slate600: [71, 85, 105] as [number, number, number],
  slate200: [226, 232, 240] as [number, number, number],
  slate50: [248, 250, 252] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
  redLight: [254, 226, 226] as [number, number, number],
  amber: [245, 158, 11] as [number, number, number],
  amberLight: [254, 243, 199] as [number, number, number],
  emerald: [5, 150, 105] as [number, number, number],
  emeraldLight: [209, 250, 229] as [number, number, number],
  blue: [37, 99, 235] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

function hex(color: [number, number, number]): string {
  return `#${color.map(c => c.toString(16).padStart(2, '0')).join('')}`;
}

function addPageNumber(doc: jsPDF) {
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pw = doc.internal.pageSize.getWidth();
    const ph = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.slate600);
    doc.text(`Page ${i} of ${pageCount}`, pw - 15, ph - 8, { align: 'right' });
    doc.text('Student Signal — Confidential', 15, ph - 8);
  }
}

function coverPage(doc: jsPDF, data: ReportData) {
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();

  // Background
  doc.setFillColor(...BRAND.slate900);
  doc.rect(0, 0, pw, ph, 'F');

  // Top accent bar
  doc.setFillColor(...BRAND.teal);
  doc.rect(0, 0, pw, 6, 'F');

  // School signal logo area
  doc.setFillColor(...BRAND.teal);
  doc.roundedRect(pw / 2 - 20, 50, 40, 40, 6, 6, 'F');
  doc.setFontSize(22);
  doc.setTextColor(...BRAND.white);
  doc.setFont('helvetica', 'bold');
  doc.text('SS', pw / 2, 76, { align: 'center' });

  // School name
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 200, 220);
  doc.text(data.schoolName || 'Student Signal', pw / 2, 108, { align: 'center' });

  // Report title
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.white);
  doc.text(data.reportType, pw / 2, 132, { align: 'center' });

  // Subtitle line
  doc.setFillColor(...BRAND.teal);
  doc.rect(pw / 2 - 30, 137, 60, 2, 'F');

  // Date / generated by
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(160, 180, 200);
  doc.text(data.date, pw / 2, 150, { align: 'center' });
  if (data.generatedBy) {
    doc.text(`Generated by ${data.generatedBy}`, pw / 2, 160, { align: 'center' });
  }

  // Active filters pill / scope
  if (data.activeFilters.length > 0) {
    const filterText = `Filters: ${data.activeFilters.join(' · ')}`;
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.teal);
    const fw = doc.getTextWidth(filterText) + 12;
    doc.setFillColor(20, 40, 60);
    doc.roundedRect(pw / 2 - fw / 2, 170, fw, 10, 3, 3, 'F');
    doc.text(filterText, pw / 2, 177, { align: 'center' });
    // Students in scope note
    doc.setFontSize(7.5);
    doc.setTextColor(140, 160, 180);
    doc.text(`Scope: ${data.students.length} students matched`, pw / 2, 186, { align: 'center' });
  } else {
    doc.setFontSize(7.5);
    doc.setTextColor(140, 160, 180);
    doc.text(`All students — ${data.students.length} in scope`, pw / 2, 178, { align: 'center' });
  }

  // KPI cards strip
  const kpis = [
    { label: 'Red Priority', value: String(data.redStudents.length), color: BRAND.red },
    { label: 'Amber Watch', value: String(data.amberStudents.length), color: BRAND.amber },
    { label: 'Avg Attendance', value: `${data.avgAttendance}%`, color: data.avgAttendance < 90 ? BRAND.red : BRAND.emerald },
    { label: 'Open Actions', value: String(data.openInterventions.length), color: BRAND.blue },
    { label: 'Success Rate', value: `${data.successRate}%`, color: data.successRate >= 70 ? BRAND.emerald : BRAND.amber },
  ];
  const cardW = (pw - 30) / kpis.length;
  const cardY = ph - 80;
  kpis.forEach((kpi, idx) => {
    const cx = 15 + idx * cardW;
    doc.setFillColor(20, 35, 55);
    doc.roundedRect(cx, cardY, cardW - 4, 40, 4, 4, 'F');
    doc.setFillColor(...kpi.color);
    doc.roundedRect(cx + 4, cardY + 4, 6, 6, 2, 2, 'F');
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND.white);
    doc.text(kpi.value, cx + cardW / 2 - 2, cardY + 22, { align: 'center' });
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(140, 160, 180);
    doc.text(kpi.label, cx + cardW / 2 - 2, cardY + 32, { align: 'center' });
  });

  // Confidential footer
  doc.setFontSize(7);
  doc.setTextColor(80, 100, 120);
  doc.text('CONFIDENTIAL — For authorised school staff only. Not for external distribution.', pw / 2, ph - 10, { align: 'center' });
}

function sectionHeader(doc: jsPDF, title: string, y: number, color: [number, number, number] = BRAND.teal): number {
  const pw = doc.internal.pageSize.getWidth();
  doc.setFillColor(...color);
  doc.rect(15, y, 4, 8, 'F');
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.slate900);
  doc.text(title, 22, y + 6.5);
  doc.setDrawColor(...BRAND.slate200);
  doc.line(15, y + 10, pw - 15, y + 10);
  return y + 16;
}

function keyFindingsNarrative(doc: jsPDF, data: ReportData, y: number): number {
  y = sectionHeader(doc, 'Key Findings', y);
  const pw = doc.internal.pageSize.getWidth();

  const bullets: string[] = [];

  if (data.redStudents.length > 0) {
    bullets.push(`${data.redStudents.length} student${data.redStudents.length > 1 ? 's' : ''} are currently flagged as Red Priority and require immediate intervention.`);
  }
  if (data.amberStudents.length > 0) {
    bullets.push(`${data.amberStudents.length} student${data.amberStudents.length > 1 ? 's' : ''} on the Amber Watchlist — close monitoring recommended.`);
  }
  if (data.avgAttendance < 95) {
    bullets.push(`School-wide average attendance is ${data.avgAttendance}% — ${data.avgAttendance < 90 ? 'significantly below' : 'below'} the 95% national benchmark.`);
  }
  if (data.urgentInterventions.length > 0) {
    bullets.push(`${data.urgentInterventions.length} urgent action${data.urgentInterventions.length > 1 ? 's' : ''} require${data.urgentInterventions.length === 1 ? 's' : ''} immediate attention.`);
  }
  if (data.escalatedInterventions.length > 0) {
    bullets.push(`${data.escalatedInterventions.length} case${data.escalatedInterventions.length > 1 ? 's' : ''} have been escalated — senior staff review required.`);
  }
  if (data.successRate > 0) {
    bullets.push(`Intervention success rate: ${data.successRate}% — ${data.successRate >= 70 ? 'strong performance, well above average.' : 'further analysis recommended.'}`);
  }
  if (data.sendStudents.length > 0) {
    bullets.push(`${data.sendStudents.length} student${data.sendStudents.length > 1 ? 's' : ''} have active SEND needs recorded.`);
  }

  if (bullets.length === 0) {
    bullets.push('No significant concerns identified in the current reporting period.');
  }

  doc.setFillColor(...BRAND.slate50);
  doc.roundedRect(15, y - 2, pw - 30, bullets.length * 10 + 12, 4, 4, 'F');

  bullets.forEach((bullet, i) => {
    doc.setFillColor(...BRAND.teal);
    doc.circle(20, y + i * 10 + 3.5, 1.5, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.slate900);
    const lines = doc.splitTextToSize(bullet, pw - 50);
    doc.text(lines, 25, y + i * 10 + 5);
  });

  return y + bullets.length * 10 + 18;
}

function simpleBarChart(
  doc: jsPDF,
  data: Array<{ label: string; value: number }>,
  x: number, y: number,
  chartW: number, chartH: number,
  color: [number, number, number] = BRAND.teal,
  title: string
): number {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.slate600);
  doc.text(title, x, y);
  y += 6;

  if (data.length === 0) {
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.slate600);
    doc.text('No data available', x, y + 10);
    return y + 25;
  }

  const maxVal = Math.max(...data.map(d => d.value), 1);
  const barH = Math.min(chartH / data.length - 4, 12);
  const labelW = 50;
  const barAreaW = chartW - labelW - 20;

  data.slice(0, 8).forEach((item, i) => {
    const by = y + i * (barH + 4);
    const bw = Math.max((item.value / maxVal) * barAreaW, 2);

    // Label
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.slate600);
    const labelLines = doc.splitTextToSize(item.label, labelW - 2);
    doc.text(labelLines[0], x, by + barH / 2 + 2);

    // Bar background
    doc.setFillColor(...BRAND.slate200);
    doc.roundedRect(x + labelW, by, barAreaW, barH, 2, 2, 'F');

    // Bar fill
    doc.setFillColor(...color);
    doc.roundedRect(x + labelW, by, bw, barH, 2, 2, 'F');

    // Value label
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND.slate900);
    doc.text(String(item.value), x + labelW + bw + 3, by + barH / 2 + 2);
  });

  return y + data.slice(0, 8).length * (barH + 4) + 8;
}

export function generatePDF(data: ReportData): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();

  // ── Cover page ──────────────────────────────────────────────────────────────
  coverPage(doc, data);

  // ── Page 2: Key Findings + Recommendations ───────────────────────────────
  doc.addPage();
  let y = 20;

  y = keyFindingsNarrative(doc, data, y);

  if (data.recommendations.length > 0) {
    y = sectionHeader(doc, 'Executive Recommendations', y);
    const LEVEL_CFG: Record<string, { color: [number, number, number]; bg: [number, number, number]; label: string }> = {
      critical: { color: BRAND.red, bg: BRAND.redLight, label: 'CRITICAL' },
      high: { color: BRAND.amber, bg: BRAND.amberLight, label: 'HIGH' },
      medium: { color: BRAND.blue, bg: [219, 234, 254], label: 'MEDIUM' },
      info: { color: BRAND.teal, bg: BRAND.tealLight, label: 'INFO' },
    };
    data.recommendations.slice(0, 8).forEach((rec) => {
      const cfg = LEVEL_CFG[rec.level] || LEVEL_CFG.info;
      const boxH = 16;
      if (y + boxH > 270) { doc.addPage(); y = 20; }
      doc.setFillColor(...cfg.bg);
      doc.roundedRect(15, y, pw - 30, boxH, 3, 3, 'F');
      doc.setFillColor(...cfg.color);
      doc.roundedRect(15, y, 24, boxH, 3, 3, 'F');
      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND.white);
      doc.text(cfg.label, 27, y + boxH / 2 + 2, { align: 'center' });
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BRAND.slate900);
      doc.text(rec.title, 44, y + 6);
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...BRAND.slate600);
      const detailLines = doc.splitTextToSize(rec.detail, pw - 60);
      doc.text(detailLines[0], 44, y + 13);
      y += boxH + 4;
    });
    y += 6;
  }

  // ── Page 3: Priority Students ────────────────────────────────────────────
  const priorityStudents = [...data.redStudents, ...data.amberStudents].slice(0, 30);
  if (priorityStudents.length > 0) {
    if (y + 40 > 270) { doc.addPage(); y = 20; }
    y = sectionHeader(doc, 'Priority Students', y);

    autoTable(doc, {
      startY: y,
      head: [['Student', 'Year', 'Risk', 'Attendance', 'Behaviour', 'Open Actions']],
      body: priorityStudents.map((s) => {
        const oi = data.openInterventions.filter(i => i.student_id === s.id).length;
        const risk = data.redStudents.includes(s) ? 'Red' : 'Amber';
        return [s.name, s.year_group || '—', risk, `${s.attendance_pct ?? 95}%`, String(s.behaviour_score ?? 0), String(oi)];
      }),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: BRAND.teal, textColor: BRAND.white, fontStyle: 'bold', fontSize: 8 },
      columnStyles: {
        2: { cellWidth: 18 },
        3: { cellWidth: 22 },
        4: { cellWidth: 22 },
        5: { cellWidth: 22 },
      },
      didParseCell: (hookData) => {
        if (hookData.column.index === 2 && hookData.section === 'body') {
          const val = hookData.cell.raw as string;
          hookData.cell.styles.textColor = val === 'Red' ? BRAND.red : BRAND.amber;
          hookData.cell.styles.fontStyle = 'bold';
        }
        if (hookData.column.index === 3 && hookData.section === 'body') {
          const val = parseFloat(hookData.cell.raw as string);
          if (val < 90) hookData.cell.styles.textColor = BRAND.red;
        }
      },
      margin: { left: 15, right: 15 },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Open Interventions ───────────────────────────────────────────────────
  if (data.openInterventions.length > 0) {
    if (y + 40 > 270) { doc.addPage(); y = 20; }
    y = sectionHeader(doc, 'Open Interventions', y, BRAND.amber);

    autoTable(doc, {
      startY: y,
      head: [['Student', 'Action Type', 'Assigned To', 'Priority', 'Due Date', 'Status']],
      body: data.openInterventions.slice(0, 25).map((i) => {
        const s = data.students.find(st => st.id === i.student_id);
        return [s?.name || i.student_id, i.action_type, i.assigned_to || '—', i.priority, i.due_date || '—', i.status.replace(/_/g, ' ')];
      }),
      styles: { fontSize: 7.5, cellPadding: 2.5 },
      headStyles: { fillColor: BRAND.amber, textColor: BRAND.white, fontStyle: 'bold', fontSize: 7.5 },
      didParseCell: (hookData) => {
        if (hookData.column.index === 3 && hookData.section === 'body') {
          const val = hookData.cell.raw as string;
          if (val === 'urgent') hookData.cell.styles.textColor = BRAND.red;
          if (val === 'high') hookData.cell.styles.textColor = BRAND.amber;
        }
      },
      margin: { left: 15, right: 15 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Attendance Concerns ──────────────────────────────────────────────────
  if (data.attendanceConcerns.length > 0 && (data.activeFilters.length === 0 || data.activeFilters.includes('Attendance'))) {
    if (y + 40 > 270) { doc.addPage(); y = 20; }
    y = sectionHeader(doc, 'Attendance Concerns', y, BRAND.red);

    autoTable(doc, {
      startY: y,
      head: [['Student', 'Year', 'Attendance %', 'SEND', 'Open Actions']],
      body: data.attendanceConcerns.slice(0, 20).map(s => {
        const oi = data.openInterventions.filter(i => i.student_id === s.id).length;
        return [s.name, s.year_group || '—', `${s.attendance_pct ?? 95}%`, s.send_status || '—', String(oi)];
      }),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: BRAND.red, textColor: BRAND.white, fontStyle: 'bold', fontSize: 8 },
      didParseCell: (hookData) => {
        if (hookData.column.index === 2 && hookData.section === 'body') {
          const val = parseFloat(hookData.cell.raw as string);
          if (val < 80) hookData.cell.styles.textColor = BRAND.red;
          else if (val < 85) hookData.cell.styles.textColor = BRAND.amber;
        }
      },
      margin: { left: 15, right: 15 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Charts: Subject & Year Group ─────────────────────────────────────────
  if (data.subjectHotspots.length > 0 || data.yearGroupStats.length > 0) {
    if (y + 80 > 270) { doc.addPage(); y = 20; }
    y = sectionHeader(doc, 'Trends & Hotspots', y);
    const halfW = (pw - 40) / 2;

    if (data.subjectHotspots.length > 0) {
      const endY = simpleBarChart(doc, data.subjectHotspots.map(s => ({ label: s.subject, value: s.count })), 15, y, halfW, 70, BRAND.amber, 'Subject Hotspots (Behaviour)');
      if (data.yearGroupStats.length > 0) {
        simpleBarChart(doc, data.yearGroupStats.map(s => ({ label: s.year, value: s.redCount + s.amberCount })), 15 + halfW + 10, y, halfW, 70, BRAND.teal, 'Year Group Risk Count');
      }
      y = Math.max(endY, y + 80);
    } else if (data.yearGroupStats.length > 0) {
      y = simpleBarChart(doc, data.yearGroupStats.map(s => ({ label: s.year, value: s.redCount + s.amberCount })), 15, y, pw - 30, 70, BRAND.teal, 'Year Group Risk Count');
    }
    y += 6;
  }

  // ── Intervention Impact ──────────────────────────────────────────────────
  if (data.impactRows.length > 0) {
    if (y + 40 > 270) { doc.addPage(); y = 20; }
    y = sectionHeader(doc, 'Intervention Impact', y, BRAND.emerald);

    // Summary metrics bar
    const metrics = [
      { label: 'Closed', value: data.impactRows.length, color: BRAND.slate600 },
      { label: 'Resolved', value: data.resolutionRate + '%', color: BRAND.emerald },
      { label: 'Success rate', value: data.successRate + '%', color: BRAND.teal },
    ];
    const metW = (pw - 30) / metrics.length;
    metrics.forEach((m, i) => {
      const mx = 15 + i * metW;
      doc.setFillColor(...BRAND.slate50);
      doc.roundedRect(mx, y, metW - 4, 18, 3, 3, 'F');
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...m.color);
      doc.text(String(m.value), mx + metW / 2 - 2, y + 10, { align: 'center' });
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...BRAND.slate600);
      doc.text(m.label, mx + metW / 2 - 2, y + 16, { align: 'center' });
    });
    y += 24;

    if (data.effectivenessRows.length > 0) {
      autoTable(doc, {
        startY: y,
        head: [['Action Type', 'Used', 'Improved', 'Resolved', 'Escalated', 'Success %']],
        body: data.effectivenessRows.slice(0, 12).map(r => [r.actionType, r.timesUsed, r.improved, r.resolved, r.escalated, `${r.successRate}%`]),
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: BRAND.emerald, textColor: BRAND.white, fontStyle: 'bold', fontSize: 8 },
        columnStyles: { 5: { fontStyle: 'bold' } },
        didParseCell: (hookData) => {
          if (hookData.column.index === 5 && hookData.section === 'body') {
            const val = parseInt(hookData.cell.raw as string);
            hookData.cell.styles.textColor = val >= 70 ? BRAND.emerald : val >= 40 ? BRAND.amber : BRAND.red;
          }
        },
        margin: { left: 15, right: 15 },
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // ── Staff Development ────────────────────────────────────────────────────
  const staffWithData = data.staffRows.filter(s => s.openCount + s.completedCount > 0);
  if (staffWithData.length > 0) {
    if (y + 40 > 270) { doc.addPage(); y = 20; }
    y = sectionHeader(doc, 'Staff Workload & Development', y, BRAND.blue);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...BRAND.slate600);
    doc.text('This section is intended to support professional development and workload planning — not performance management.', 15, y);
    y += 8;

    autoTable(doc, {
      startY: y,
      head: [['Staff Member', 'Open Actions', 'Overdue', 'Completed', 'Outcome Rate', 'Development Note']],
      body: staffWithData.slice(0, 15).map(r => [r.name, r.openCount, r.overdueCount, r.completedCount, `${r.successRate}%`, r.pdLabel || 'Insufficient data']),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: BRAND.blue, textColor: BRAND.white, fontStyle: 'bold', fontSize: 8 },
      didParseCell: (hookData) => {
        if (hookData.column.index === 2 && hookData.section === 'body') {
          const val = parseInt(hookData.cell.raw as string);
          if (val > 2) hookData.cell.styles.textColor = BRAND.red;
        }
      },
      margin: { left: 15, right: 15 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── SEND section ─────────────────────────────────────────────────────────
  if (data.sendStudents.length > 0 && (data.activeFilters.length === 0 || data.activeFilters.includes('send'))) {
    if (y + 40 > 270) { doc.addPage(); y = 20; }
    y = sectionHeader(doc, 'SEND Reporting', y, BRAND.blue);

    autoTable(doc, {
      startY: y,
      head: [['Student', 'Year', 'SEND Status', 'Attendance', 'Open Actions']],
      body: data.sendStudents.slice(0, 20).map(s => {
        const oi = data.openInterventions.filter(i => i.student_id === s.id).length;
        return [s.name, s.year_group || '—', s.send_status || 'Yes', `${s.attendance_pct ?? 95}%`, String(oi)];
      }),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: BRAND.blue, textColor: BRAND.white, fontStyle: 'bold', fontSize: 8 },
      margin: { left: 15, right: 15 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Add page numbers ──────────────────────────────────────────────────────
  addPageNumber(doc);

  // ── Save ──────────────────────────────────────────────────────────────────
  const slug = data.reportType.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  doc.save(`student-signal-${slug}-${new Date().toISOString().split('T')[0]}.pdf`);
}

